### ISSUE TITLE
Benchmarker Callback Returns Negative Wall Clock Time

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#139]
In some cases (specifically when the training is fast), the `Benchmarker` callback returns a negative wall clock time. Specifically, the wall clock time seems to be the negative of the step number in these cases. 

** To reproduce

Run `python examples/run_mosaic_trainer.py -f composer/yamls/models/classify_mnist.yaml` with the default benchmarker callback hparams.

The yaml file should look like this:
```
train_dataset:
  mnist:
    is_train: true
    datadir: /datasets/mnist
    download: true
    shuffle: true
    drop_last: true
val_dataset:
  mnist:
    is_train: false
    datadir: /datasets/mnist
    download: true
    shuffle: false
    drop_last: false
optimizer:
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1.0e-4
schedulers:
  - cosine_decay:
      T_max: "10ep"
model:
  mnist_classifier:
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 10
loggers:
  - file: {}
max_epochs: 5
total_batch_size: 2048
eval_batch_size: 1000
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
validate_every_n_epochs: 1
grad_accum: 1
precision: amp
callbacks:
  benchmarker: {}
```

The output will be as follows:

```
[EPOCH][step=29]: { "wall_clock_train": -29.0000, }
[EPOCH][step=29]: { "accuracy/val": 0.9089, }
[EPOCH][step=29]: { "crossentropyloss/val": 0.5204, }
[EPOCH][step=29]: { "epoch": 1, }
[EPOCH][step=145]: { "wall_clock_train": -145.0000, }
[EPOCH][step=145]: { "accuracy/val": 0.9538, }
[EPOCH][step=145]: { "crossentropyloss/val": 0.1432, }
```

## Expected behavior

Wall clock time should be positive.
