### ISSUE TITLE
Composer logging crashes with Falcon-7B model

### ISSUE THREAD

**Issue by tginart** [mosaicml/composer#2289]
** Environment **
Env is mosaicml/llm-foundry:2.0.1_cu118-latest

** To reproduce

Use example .yaml but for falcon-7b
```

integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  # git_branch: # use your branch
  # git_commit: # OR use your commit hash
  pip_install: -e .[gpu]
  ssh_clone: false # Should be true if using a private repo

command: |
  cd llm-foundry/scripts
  python data_prep/convert_dataset_hf.py \
    --dataset c4 --data_subset en \
    --out_root ./my-copy-c4 --splits train_small val_small \
    --concat_tokens 2048 --tokenizer tiiuae/falcon-7b --eos_text '<|endoftext|>'
  composer train/train.py /mnt/config/parameters.yaml
image: mosaicml/llm-foundry:2.0.1_cu118-latest
# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $COMPOSER_RUN_NAME
run_name: mosaic-gpt-7b-gpus-8

gpu_num: 8
cluster: r8z6 # replace with your cluster here!

parameters:

  max_seq_len: 2048
  global_seed: 17
  data_local: ./my-copy-c4
  tokenizer_name: tiiuae/falcon-7b


  # Run Name
  run_name: # If left blank, will be read from env var $COMPOSER_RUN_NAME

  # Model
  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: tiiuae/falcon-7b
    pretrained: true

  # Tokenizer
  tokenizer:
    name: ${tokenizer_name}
    kwargs:
      model_max_length: ${max_seq_len}

  train_loader:
    name: text
    dataset:
      local: ${data_local}
      split: train_small
      allow_pad_trimming: false
      decoder_only_format: true
      shuffle: true
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: true
    num_workers: 8

  # There is no validation split so we skip eval_loader

  # Optimization
  scheduler:
    name: linear_decay_with_warmup # linear no warmup is HF default which dolly used
    t_warmup: 30ba
    alpha_f: 0.1

  optimizer:
    # mimic HF defaults to replicate dolly
    name: decoupled_adamw
    lr: 2.0e-5
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-8
    weight_decay: 0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 2ba
  eval_interval: 1 # this is the only allowed value for no eval
  # eval_first: false
  # eval_subset_num_batches: -1
  global_train_batch_size: 32 # assuming 8 gpus

  # System
  seed: ${global_seed}
  device_eval_batch_size: 2
  device_train_microbatch_size: 2
  # device_train_microbatch_size: auto
  precision: amp_bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  # Logging
  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    runtime_estimator: {}

  loggers:
     wandb: {}

  # Checkpoint to local filesystem or remote object store
  save_interval: 1ba
  save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
  # save_folder: ./{run_name}/checkpoints
  save_folder: <path-here>

  # Load from remote object store
  # REPLACE THE BELOW with you own checkpoint!
  # load_path: oci://my-bucket/my-folder/mpt-7b/checkpoints/some_checkpoint.pt

```

Observe the bug:

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /llm-foundry/scripts/train/train.py:259 in <module>                          │
│                                                                              │
│   256 │   │   yaml_cfg = om.load(f)                                          │
│   257 │   cli_cfg = om.from_cli(args_list)                                   │
│   258 │   cfg = om.merge(yaml_cfg, cli_cfg)                                  │
│ ❱ 259 │   main(cfg)                                                          │
│   260                                                                        │
│                                                                              │
│ /llm-foundry/scripts/train/train.py:248 in main                              │
│                                                                              │
│   245 │   │   trainer.eval()                                                 │
│   246 │                                                                      │
│   247 │   print('Starting training...')                                      │
│ ❱ 248 │   trainer.fit()                                                      │
│   249 │                                                                      │
│   250 │   print('Done.')                                                     │
│   251                                                                        │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/trainer/trainer.py:1766 in fit       │
│                                                                              │
│   1763 │   │   │   self.state.scaler = ClosureGradScaler() if self._use_clos │
│   1764 │   │                                                                 │
│   1765 │   │   self.first_batch_complete = False                             │
│ ❱ 1766 │   │   self._train_loop()                                            │
│   1767 │                                                                     │
│   1768 │   def close(self):                                                  │
│   1769 │   │   """Shutdown the trainer.                                      │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/trainer/trainer.py:1996 in           │
│ _train_loop                                                                  │
│                                                                              │
│   1993 │   │   │   │   │   self._run_evaluators(Event.BATCH_END)             │
│   1994 │   │   │   │   │   last_wct = datetime.datetime.now() - duration     │
│   1995 │   │   │   │   │                                                     │
│ ❱ 1996 │   │   │   │   │   self.engine.run_event(Event.BATCH_CHECKPOINT)     │
│   1997 │   │   │   │   │                                                     │
│   1998 │   │   │   │   │   if self.state.timestamp >= self.state.max_duratio │
│   1999 │   │   │   │   │   │   # If max_duration is specified in batches, sa │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/engine.py:293 in run_event      │
│                                                                              │
│   290 │   │   │   traces = self._run_algorithms(event)                       │
│   291 │   │   │   # Run callbacks first, so any log calls from a callback th │
│   292 │   │   │   # get registered before they are flushed by the logger its │
│ ❱ 293 │   │   │   self._run_nonlogger_callbacks(event)                       │
│   294 │   │   │   self._run_loggers(event)                                   │
│   295 │   │                                                                  │
│   296 │   │   if event.is_before_event and duration_marker is not None:      │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/engine.py:475 in                │
│ _run_nonlogger_callbacks                                                     │
│                                                                              │
│   472 │                                                                      │
│   473 │   def _run_nonlogger_callbacks(self, event: Union[Event, str]):      │
│   474 │   │   callbacks = [callback for callback in self.state.callbacks if  │
│ ❱ 475 │   │   self._run_callbacks(event, callbacks)                          │
│   476 │                                                                      │
│   477 │   def __del__(self):                                                 │
│   478 │   │   global _did_atexit_run                                         │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/engine.py:467 in _run_callbacks │
│                                                                              │
│   464 │   │   │   ctx = cast(ContextManager, contextlib.nullcontext()) if ma │
│   465 │   │   │   with ctx:                                                  │
│   466 │   │   │   │   self._debug_log(event, f'Running callback {type(cb).__ │
│ ❱ 467 │   │   │   │   cb.run_event(event, self.state, self.logger)           │
│   468 │                                                                      │
│   469 │   def _run_loggers(self, event: Union[Event, str]):                  │
│   470 │   │   loggers = [callback for callback in self.state.callbacks if is │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/callback.py:96 in run_event     │
│                                                                              │
│    93 │   │   │   logger (Logger): The logger.                               │
│    94 │   │   """                                                            │
│    95 │   │   event_cb = getattr(self, event.value)                          │
│ ❱  96 │   │   return event_cb(state, logger)                                 │
│    97 │                                                                      │
│    98 │   def init(self, state: State, logger: Logger) -> None:              │
│    99 │   │   """Called on the :attr:`.Event.INIT` event.                    │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/callbacks/checkpoint_saver.py:346 in │
│ batch_checkpoint                                                             │
│                                                                              │
│   343 │   def batch_checkpoint(self, state: State, logger: Logger):          │
│   344 │   │   assert callable(self.save_interval)                            │
│   345 │   │   if self.save_interval(state, Event.BATCH_CHECKPOINT) and self. │
│ ❱ 346 │   │   │   self._save_checkpoint(                                     │
│   347 │   │   │   │   state,                                                 │
│   348 │   │   │   │   logger,                                                │
│   349 │   │   │   )                                                          │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/callbacks/checkpoint_saver.py:384 in │
│ _save_checkpoint                                                             │
│                                                                              │
│   381 │   │   # save the checkpoint to the filename                          │
│   382 │   │   filename = self.filename.format(state, is_deepspeed)           │
│   383 │   │                                                                  │
│ ❱ 384 │   │   saved_path = checkpoint.save_checkpoint(                       │
│   385 │   │   │   state=state,                                               │
│   386 │   │   │   filename=filename,                                         │
│   387 │   │   │   weights_only=self.weights_only,                            │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/utils/checkpoint.py:518 in           │
│ save_checkpoint                                                              │
│                                                                              │
│   515 │   is_deepspeed = is_model_deepspeed(state.model)                     │
│   516 │                                                                      │
│   517 │   state_dict = {                                                     │
│ ❱ 518 │   │   'state': state.state_dict(),                                   │
│   519 │   │   'rng': reproducibility.get_rng_state(),                        │
│   520 │   }                                                                  │
│   521 │   if weights_only and not is_deepspeed:                              │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/state.py:802 in state_dict      │
│                                                                              │
│    799 │   │   │   │   if self.fsdp_enabled and self.fsdp_state_dict_type is │
│    800 │   │   │   │   │   optim_state_dict = {                              │
│    801 │   │   │   │   │   │   type(optimizer).__qualname__:                 │
│ ❱  802 │   │   │   │   │   │   │   fsdp_get_optim_state_dict(self.model, opt │
│    803 │   │   │   │   │   }                                                 │
│    804 │   │   │   │   else:                                                 │
│    805 │   │   │   │   │   optim_state_dict = {type(optimizer).__qualname__: │
│                                                                              │
│ /usr/lib/python3/dist-packages/composer/core/state.py:127 in                 │
│ fsdp_get_optim_state_dict                                                    │
│                                                                              │
│    124 │   │   optim_state_dict = _legacy_fsdp_get_optim_state_dict(model, o │
│    125 │   else:                                                             │
│    126 │   │   with fsdp_state_dict_type_context(module=model, state_dict_ty │
│ ❱  127 │   │   │   optim_state_dict = FSDP.optim_state_dict(model, optim)  # │
│    128 │   return optim_state_dict                                           │
│    129                                                                       │
│    130                                                                       │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_par │
│ allel.py:1753 in optim_state_dict                                            │
│                                                                              │
│   1750 │   │   │   ``state_dict_type``.                                      │
│   1751 │   │   """                                                           │
│   1752 │   │   state_dict_settings = FullyShardedDataParallel.get_state_dict │
│ ❱ 1753 │   │   return FullyShardedDataParallel._optim_state_dict_impl(       │
│   1754 │   │   │   model=model,                                              │
│   1755 │   │   │   optim=optim,                                              │
│   1756 │   │   │   optim_state_dict=optim.state_dict(),                      │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_par │
│ allel.py:1154 in _optim_state_dict_impl                                      │
│                                                                              │
│   1151 │   │   │   for m in FullyShardedDataParallel.fsdp_modules(model)     │
│   1152 │   │   ), "Not all FSDP modules have the same _use_orig_params value │
│   1153 │   │                                                                 │
│ ❱ 1154 │   │   return _optim_state_dict(                                     │
│   1155 │   │   │   model=model,                                              │
│   1156 │   │   │   optim=optim,                                              │
│   1157 │   │   │   optim_state_dict=optim_state_dict,                        │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_optim_utils.py:1455   │
│ in _optim_state_dict                                                         │
│                                                                              │
│   1452 │   │   │   │   │   {} if param_key is None else optim_state_dict["st │
│   1453 │   │   │   │   )                                                     │
│   1454 │   │   │   │   unflat_state = [                                      │
│ ❱ 1455 │   │   │   │   │   _gather_orig_param_state(                         │
│   1456 │   │   │   │   │   │   fsdp_param_info,                              │
│   1457 │   │   │   │   │   │   fqn,                                          │
│   1458 │   │   │   │   │   │   state,                                        │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_optim_utils.py:1690   │
│ in _gather_orig_param_state                                                  │
│                                                                              │
│   1687 │   ):                                                                │
│   1688 │   │   return optim_state                                            │
│   1689 │                                                                     │
│ ❱ 1690 │   gathered_state = _all_gather_optim_state(fsdp_state, optim_state) │
│   1691 │                                                                     │
│   1692 │   # Unflatten state values.                                         │
│   1693 │   for state_name, value in list(gathered_state.items()):            │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_optim_utils.py:1637   │
│ in _all_gather_optim_state                                                   │
│                                                                              │
│   1634 │   for rank, object_state in enumerate(object_list):                 │
│   1635 │   │   if rank in empty_ranks:                                       │
│   1636 │   │   │   continue                                                  │
│ ❱ 1637 │   │   for name, non_tensor_value in object_state.non_tensors.items( │
│   1638 │   │   │   curr_non_tensor_value = gathered_state.get(name, None)    │
│   1639 │   │   │   assert (                                                  │
│   1640 │   │   │   │   curr_non_tensor_value is None                         │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'int' object has no attribute 'items'
```

## Expected behavior

Note that training actually works without issue. The problem comes in when saving a checkpoint.

It seems like this is purely a Composer issue (not using llm-foundry code) so wondering if Composer check-pointing might support Falcon-7b (or what is a suggested patch to make it work).
